source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'dotenv-rails', groups: [:development, :test]

gem 'rails', '~> 6.0.3'
gem 'puma', '~> 4.3.12'
gem 'jbuilder', '~> 2.10'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.6', require: false

gem 'mongo', '~> 2.12.1'
gem 'redis', '~> 4.1.4'
gem 'redlock'

group :development do
  gem 'web-console', '>= 4.0.2'
  gem 'listen', '3.2.1'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.1'
  gem 'pry-rails', '~> 0.3.9'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.7'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
